### ISSUE TITLE
Should add a property to change label when task is running.

### ISSUE THREAD

**Issue by uahnbu** [actboy168/vscode-tasks#27]

**Comment by alexzshl** [comment]
Is this what you expect? Or you can suggest better
![test](https://user-images.githubusercontent.com/39125296/105040802-417cdf00-5a9d-11eb-9681-fdfb4b18b905.gif)

**Comment by uahnbu** [comment]
I'm using vstasks to watch files (running npm-run-all pug sass ts --watch) so it would be good if there's some signal that the terminal is still watching. A spinning icon like in the image above is great.

**Comment by henrikxberg** [comment]
I'd like to add that while this functionality would be great, maybe not with distracting animations since tasks might be active all day. If possible, I'd prefer to be able to set an alternative label and/or color while a task is running. I'd also like the option to terminate the task by clicking it while it is active.
Thanks for a great extension.
